name: packrat
favicon: null
layout_spectrum: 0.64117
typography_spectrum: 0.50109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#052524'
    - '#384b51'
    - '#686c77'
    - '#a49cab'
    - '#ad8645'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
