favicon: null
name: packrat
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2419355
  brandStrength: 0
  lightness: 0.4784946
  brandColors:
    - '#052524'
    - '#384b51'
    - '#686c77'
    - '#a49cab'
    - '#ad8645'
  rhythmicContrast: 0
typography_spectrum: 0.50109
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 0.6492
