favicon: null
name: packrat
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.09139785
  brandStrength: 0
  lightness: 0.5286738
  brandColors:
    - '#6E605D'
    - '#D9C2B0'
    - '#9C8072'
    - '#4971A6'
    - '#8597B6'
  rhythmicContrast: 0
typography_spectrum: 0.50109
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6492
analytics:
  twitter: null
  google: null
  facebook: null
