name: packrat
favicon: null
layout_spectrum: 0.12814440880902112
typography_spectrum: 0.5835929769091308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12052300642244518
  lightness: 0.026465426431968808
  saturation: 0.08425381709821522
  rhythmicContrast: 0.9225412933155894
purpose: []
